---
name: ELIAS1731 Custom Ingress App
version: dev
slug: ingress_proxy
description: "Simple tool to get YOUR page implemented in HA"
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
init: false
ingress: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl
options:
  destination: "http://192.168.0.1"
schema:
  destination: str?
