arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: Elias Custom Nginx Proxy Manager
hassio_api: true
image: ghcr.io/hassio-addons/nginxproxymanager/{arch}
init: false
map:
- ssl:rw
- backup:rw
name: Elias Custom NPM
ports:
  80/tcp: 80
  81/tcp: 81
  443/tcp: 443
  6061/tcp: 6061
  6062/tcp: 6062
  6063/tcp: 6063
  6064/tcp: 6064
ports_description:
  80/tcp: HTTP Entrance port
  81/tcp: Proxy management web interface
  443/tcp: HTTPS/SSL Entrance port
  6061/tcp: Vaultwarden web interface
  6062/tcp: EXTRAPORT 1 free to use
  6063/tcp: EXTRAPORT 2 free to use
  6064/tcp: EXTRAPORT 3 free to use
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  reset_database: bool?
services:
- mysql:need
slug: elias-custom-npm
url: https://github.com/elias1731/elias-custom-ha-repo/
version: 0.12.2
webui: http://[HOST]:[PORT:81]
